[workspace]
members = [".", "e2e"]
resolver = "2"

[package]
name = "guix-p2p"
version = "0.1.13"
edition = "2024"
description = "P2P binary substitute distribution for GNU Guix"
license = "GPL-3.0-or-later"

[dependencies]
libp2p = { version = "0.56", features = ["full", "kad", "quic", "tcp", "dns", "request-response", "mdns", "identify", "macros", "autonat", "relay"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
ed25519-dalek = "2"
libgcrypt-sys = "0.7"
sha2 = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bitvec = "1"
anyhow = "1"
base64 = "0.22"
hex = "0.4"
serde_bytes = "0.11"
futures = "0.3"
libc = "0.2"
thiserror = "2"
axum = { version = "0.7", features = ["ws"] }
toml = "0.8"
toml_edit = "0.22"
flate2 = "1"
zstd = "0.13"
tokio-util = { version = "0.7", features = ["io"] }
lzma-rust2 = { version = "0.16", default-features = false, features = ["std", "lzip"] }
leaky-bucket = "1.1"
if-addrs = "0.15"

[dev-dependencies]
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
